'use client'

import '../../career-detail.css'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useLanguage } from '@/context/LanguageContext'
import { JOB_DETAIL_QUERY } from '@/sanity/lib/queries'
import { getImageUrl } from '@/sanity/lib/image'
import { useSanityContent } from '@/sanity/lib/fetchData'

const labels = { en: { home: 'Home', careers: 'Careers', jobTitle: 'Job Title', company: 'Company', department: 'Department', reportsTo: 'Reports To', sector: 'Sector', location: 'Country / City', employment: 'Employment Type', experience: 'Experience', education: 'Education', language: 'Language', description: 'JOB DESCRIPTION', summary: 'Job Summary', responsibilities: 'KEY RESPONSIBILITIES', responsibilitiesTitle: 'Key Responsibilities', qualifications: 'EDUCATION & QUALIFICATIONS', qualificationsTitle: 'Education & Qualifications', requirements: 'EXPERIENCE REQUIREMENTS', requirementsTitle: 'Experience Requirements', environment: 'WORK ENVIRONMENT', environmentTitle: 'Work Environment', apply: 'Apply for this vacancy', applyIntro: 'Send your CV and our recruitment team will review your application.', name: 'Full name', email: 'Email', phone: 'Phone', resume: 'Resume / CV', message: 'Message', submit: 'Submit application', sending: 'Sending…', success: 'Your application was submitted successfully.', closed: 'This vacancy is closed.', error: 'Could not submit the application.' }, ar: { home: 'الرئيسية', careers: 'الوظائف', jobTitle: 'المسمى الوظيفي', company: 'الشركة', department: 'القسم', reportsTo: 'يرفع التقارير إلى', sector: 'القطاع', location: 'الدولة / المدينة', employment: 'نوع التوظيف', experience: 'الخبرة', education: 'التعليم', language: 'اللغة', description: 'وصف الوظيفة', summary: 'ملخص الوظيفة', responsibilities: 'المسؤوليات الرئيسية', responsibilitiesTitle: 'المسؤوليات الرئيسية', qualifications: 'التعليم والمؤهلات', qualificationsTitle: 'التعليم والمؤهلات', requirements: 'متطلبات الخبرة', requirementsTitle: 'متطلبات الخبرة', environment: 'بيئة العمل', environmentTitle: 'بيئة العمل', apply: 'التقدم لهذه الوظيفة', applyIntro: 'أرسل سيرتك الذاتية وسيقوم فريق التوظيف بمراجعة طلبك.', name: 'الاسم الكامل', email: 'البريد الإلكتروني', phone: 'الهاتف', resume: 'السيرة الذاتية', message: 'رسالة', submit: 'إرسال الطلب', sending: 'جارٍ الإرسال…', success: 'تم إرسال طلبك بنجاح.', closed: 'هذه الوظيفة مغلقة.', error: 'تعذر إرسال الطلب.' } }
function localized(lang, ar, en) { return lang === 'ar' ? (ar || en || '') : (en || ar || '') }
function lines(value) { return String(value || '').split(/\r?\n/).map((item) => item.replace(/^\s*[-•*]\s*/, '').trim()).filter(Boolean) }
function DetailSection({ label, title, text, list = false }) { if (!text) return null; return <section className="job-detail-section"><p className="job-detail-kicker">{label}<span /></p><h2>{title}</h2>{list ? <ul>{lines(text).map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul> : <p>{text}</p>}</section> }

export default function JobDetailPage() {
  const { lang } = useLanguage(); const copy = labels[lang] || labels.en; const params = useParams(); const slug = params?.slug || ''; const job = useSanityContent('jobDetail', JOB_DETAIL_QUERY, { slug })
  if (!job) return <main className="job-detail-page"><div className="job-detail-loading">Loading vacancy…</div></main>
  const title = localized(lang, job.titleAr, job.titleEn); const department = localized(lang, job.departmentAr, job.departmentEn); const sector = localized(lang, job.sectorAr, job.sectorEn); const heroImage = job.heroImage ? getImageUrl(job.heroImage, '/images/careers_engineers_hero.webp') : '/images/careers_engineers_hero.webp'
  const details = [[copy.jobTitle, title], [copy.company, localized(lang, job.companyAr, job.companyEn)], [copy.department, department], [copy.reportsTo, localized(lang, job.reportsToAr, job.reportsToEn)], [copy.sector, sector], [copy.location, localized(lang, job.locationAr, job.locationEn)], [copy.employment, localized(lang, job.employmentTypeAr, job.employmentType)], [copy.experience, localized(lang, job.experienceAr, job.experienceEn)], [copy.education, localized(lang, job.educationAr, job.educationEn)], [copy.language, localized(lang, job.languageAr, job.languageEn)]].filter(([, value]) => value)
  const mailSubject = encodeURIComponent(`Application: ${title}`)
  const mailBody = encodeURIComponent(`Hello HR team,\n\nI would like to apply for the ${title} position. Please find my CV attached.\n\nKind regards,`)
  const applyNowLabel = lang === 'ar' ? '\u062a\u0642\u062f\u0645 \u0627\u0644\u0622\u0646' : 'Apply Now'
  return <main className="job-detail-page" lang={lang} dir={lang === 'ar' ? 'rtl' : 'ltr'}><section className="job-detail-hero"><img src={heroImage} alt={title} /><div className="job-detail-hero-overlay"><div className="job-detail-hero-content"><p className="job-breadcrumb"><Link href="/">{copy.home}</Link><span>/</span><Link href="/careers">{copy.careers}</Link><span>/</span>{title}</p><h1>{title}</h1><p className="job-detail-department">{department}{sector && <> <span>/</span> {sector}</>}</p><p className="job-detail-intro">{localized(lang, job.descriptionAr, job.descriptionEn)}</p></div></div></section><section className="job-facts-card">{details.map(([label, value]) => <div key={label}><span className="job-fact-icon">⌁</span><small>{label}</small><strong>{value}</strong></div>)}</section><section className="job-detail-content"><div><DetailSection label={copy.description} title={copy.summary} text={localized(lang, job.summaryAr, job.summaryEn) || localized(lang, job.descriptionAr, job.descriptionEn)} /><DetailSection label={copy.responsibilities} title={copy.responsibilitiesTitle} text={localized(lang, job.responsibilitiesAr, job.responsibilitiesEn)} list /></div><div><DetailSection label={copy.qualifications} title={copy.qualificationsTitle} text={localized(lang, job.qualificationsAr, job.qualificationsEn)} list /><DetailSection label={copy.requirements} title={copy.requirementsTitle} text={localized(lang, job.experienceRequirementsAr, job.experienceRequirementsEn) || localized(lang, job.requirementsAr, job.requirementsEn)} list /><DetailSection label={copy.environment} title={copy.environmentTitle} text={localized(lang, job.workEnvironmentAr, job.workEnvironmentEn)} list /></div></section><section className="job-detail-apply"><div><h2>{copy.apply}</h2><p>{job.isOpen === false ? copy.closed : copy.applyIntro}</p></div>{job.isOpen !== false && <a className="job-application-button" href={`mailto:hr@almatar-oil.com?subject=${mailSubject}&body=${mailBody}`}>{applyNowLabel}<span aria-hidden="true">→</span></a>}</section></main>
}
