'use client';

import { useEffect } from 'react';
import RelatedPoliciesCarousel from '@/components/RelatedPoliciesCarousel';

function useReveal() {
  useEffect(() => {
    const items = document.querySelectorAll('[data-scroll-reveal]');
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); }
    }), { threshold: 0.08 });
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, []);
}

const icons = {
  file: <><path d="M6 3h8l4 4v14H6V3Z" fill="none" stroke="currentColor" strokeWidth="1.8"/><path d="M14 3v5h4M9 12h6m-6 4h6" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></>,
  people: <><circle cx="12" cy="8" r="3" fill="none" stroke="currentColor" strokeWidth="1.8"/><circle cx="5.5" cy="11" r="2.2" fill="none" stroke="currentColor" strokeWidth="1.6"/><circle cx="18.5" cy="11" r="2.2" fill="none" stroke="currentColor" strokeWidth="1.6"/><path d="M5 20c.3-3.5 2.4-5.3 7-5.3s6.7 1.8 7 5.3M2 19c.2-2.4 1.3-3.7 3.5-3.7M22 19c-.2-2.4-1.3-3.7-3.5-3.7" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/></>,
  briefcase: <><rect x="4" y="7" width="16" height="13" rx="2" fill="none" stroke="currentColor" strokeWidth="1.8"/><path d="M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2M4 12h16M10 12v2h4v-2" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></>,
  gear: <><path d="m12 3 1.1 2 2.2.5 1.8-1 1.5 1.5-1 1.8.5 2.2 2 1.1v2l-2 1.1-.5 2.2 1 1.8-1.5 1.5-1.8-1-2.2.5-1.1 2h-2l-1.1-2-2.2-.5-1.8 1-1.5-1.5 1-1.8-.5-2.2-2-1.1v-2l2-1.1.5-2.2-1-1.8L6.7 4.5l1.8 1 2.2-.5L12 3Z" fill="none" stroke="currentColor" strokeWidth="1.7"/><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" strokeWidth="1.7"/></>,
  shield: <><path d="M12 3 19 6v5c0 4.6-2.9 8.5-7 10-4.1-1.5-7-5.4-7-10V6l7-3Z" fill="none" stroke="currentColor" strokeWidth="1.8"/><path d="m8.5 12 2.2 2.2 4.8-5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></>,
  handshake: <><path d="m3 10 3-3 4 1 2-2 4 1 5 5-3 3-3-2-3 3-3-2-2 2-4-4 3-2Z" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/><path d="m10 8 3 3m-1 4 2-2m-5 0 2-2" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></>,
  bars: <><path d="M5 20v-5h3v5H5Zm5 0V9h3v11h-3Zm5 0V4h3v16h-3Z" fill="currentColor"/></>,
  lock: <><rect x="5" y="10" width="14" height="11" rx="1" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="12" cy="15" r="1" fill="currentColor"/></>,
  pen: <><path d="m4 20 1.5-5.5L16.5 3.5a2.1 2.1 0 0 1 3 3L8.5 17.5 4 20Z" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round"/><path d="m14 6 4 4M3 22h9" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></>,
  target: <><circle cx="12" cy="12" r="8" fill="none" stroke="currentColor" strokeWidth="1.8"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" strokeWidth="1.8"/><circle cx="12" cy="12" r="1.5" fill="currentColor"/><path d="m16 8 5-5m-4 0h4v4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></>,
};
function Icon({ name }) { return <span className="confidentiality-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none">{icons[name]}</svg></span>; }

const sections = [
  ['file', 'Employment Affairs and Workplace Conduct Policy', 'We believe at AL-MATAR Company that the human competencies and technical expertise of our employees are the fundamental pillar for our continued success in the oil, well services, and civil works sector. Therefore, the key to our success lies in our ability to attract, train, motivate, and retain qualified personnel, while providing a work environment based on mutual respect and fairness. The company adopts and encourages a fair employment policy without discrimination across all its branches, and all decisions relating to recruitment, promotion, compensation, transfer, and termination are made in an objective and honest manner, based solely on competence, experience, and performance—not on tribe, religion, sect, gender, or age.'],
  ['people', 'Respectful and Fair Workplace', 'The company is committed to providing a work environment free from all forms of harassment. All employees must demonstrate full respect for their colleagues and avoid any hostile behavior, bullying, verbal or physical insults. The company also maintains a clear policy regarding the hiring of relatives.'],
  ['briefcase', 'Employment and Supervision Standards', 'While the company does not object to hiring relatives of current employees (provided the required qualifications are met), it is strictly prohibited for an employee to directly supervise a relative (such as a brother, cousin, or uncle) within the same drilling crew or same administrative site, in order to avoid any potential conflict of interest or favoritism in evaluations. The company does not typically rehire any employee whose services were previously terminated for disciplinary reasons.'],
  ['gear', 'Management and HR Responsibilities', 'The responsibility for implementing this policy lies with direct management and human resources managers, who are tasked with overseeing continuous training programs for drilling crews, mechanics, and supervisors to ensure the refinement of their technical skills and adherence to required safety and ethical standards.'],
  ['shield', 'Confidential Complaints and Discipline', 'Any complaint or issue relating to a violation of this policy will be handled with complete confidentiality and investigated impartially.\n\nAny violation of this policy may subject the employee to disciplinary action, including warning, transfer, salary reduction, or final termination, depending on the severity of the violation.'],
];

const focus = [['people', 'Fair\nEmployment', 'Equal opportunity\nfor all.'], ['handshake', 'Workplace\nRespect', 'A professional\nand inclusive culture.'], ['shield', 'Anti-Harassment', 'A safe and\ndignified workplace.'], ['people', 'No Favoritism', 'Merit over\npersonal relationships.'], ['bars', 'Training &\nDevelopment', 'Building skills\nfor a stronger future.'], ['lock', 'Confidential\nComplaints', 'Speak up.\nWe listen.'], ['file', 'Disciplinary\nAccountability', 'A fair and consistent\nprocess.']];

export default function EmploymentAffairsPage() {
  useReveal();
  return <main className="confidentiality-page employment-policy-page">
    <section className="confidentiality-hero"><img src="/images/policies-photo/Employment-affairs-workplace-conduct-hero.png" alt="AL-MATAR employment affairs and workplace conduct" /><div className="confidentiality-hero-overlay"><div className="confidentiality-hero-breadcrumb">Home&nbsp; / &nbsp;Policies&nbsp; / &nbsp;Employment Affairs Policy</div><h1>Employment Affairs and<br />Workplace Conduct Policy</h1><p>Building a respectful, fair and skilled workforce<br className="desktop-only" /> across every operation.</p><span className="confidentiality-rule" /><strong>PEOPLE&nbsp;&nbsp; | &nbsp;&nbsp;SAFETY&nbsp;&nbsp; | &nbsp;&nbsp;OPERATIONAL EXCELLENCE</strong><div className="confidentiality-hero-message">PEOPLE<br />RESPECT<br />INTEGRITY<br />A STRONGER<br />TOMORROW</div></div></section>
    <div className="confidentiality-layout"><section className="confidentiality-document"><div className="confidentiality-sections">{sections.map(([icon, title, text], index) => <article className="confidentiality-section policy-reveal" data-scroll-reveal key={title} style={{ '--reveal-delay': `${index * 70}ms` }}><Icon name={icon} /><div><h2>{title}</h2>{text.split('\n\n').map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></article>)}<div className="confidentiality-signature"><Icon name="pen" /><div><strong>Suliman Mattar Yousef</strong><span>Chairman of the Board and CEO, AL-MATAR Company</span></div></div></div></section><aside className="confidentiality-sidebar"><section className="confidentiality-info"><h2><Icon name="file" /> Policy Information</h2><dl><div><dt>Policy No.:</dt><dd>3</dd></div><div><dt>Document Code:</dt><dd>AM-HR-L001</dd></div><div><dt>Issued on:</dt><dd>January 1, 2025</dd></div><div><dt>Last Updated:</dt><dd>August 18, 2026</dd></div><div><dt>Location:</dt><dd>Qamishli, Syria</dd></div><div><dt>Contact:</dt><dd>Human Resources Manager</dd></div></dl><a href="#focus-areas" className="confidentiality-view">◉ &nbsp; View Policy Document <span>→</span></a><a href="#focus-areas" className="confidentiality-download">⇩ &nbsp; Download PDF</a></section><section className="confidentiality-commitment"><h2><Icon name="shield" /> Our Commitment</h2><p>Fair employment.<br />Respect at work.<br />Skilled teams.<br />A stronger tomorrow.</p><div>We believe our people are the foundation of our success. By fostering a fair, respectful and inclusive workplace, we build stronger teams and create lasting value for our clients, our communities and a brighter tomorrow.</div><img src="/images/policies-photo/Employment-affairs-workplace-conduct-page.png" alt="AL-MATAR team walking at an oilfield" /></section></aside></div>
    <section className="confidentiality-focus" id="focus-areas"><div className="confidentiality-focus-heading"><span /><h2><Icon name="target" /> Key Workplace Focus Areas</h2><span /></div><div className="confidentiality-focus-grid employment-focus-grid">{focus.map(([icon, title, text]) => <article key={title}><Icon name={icon} /><h3>{title.split('\n').map((line) => <span key={line}>{line}</span>)}</h3><p>{text.split('\n').map((line) => <span key={line}>{line}</span>)}</p></article>)}</div></section>
    <RelatedPoliciesCarousel currentPath="/policies/employment-affairs-workplace-conduct" />
  </main>;
}
