import { defineField, defineType } from 'sanity'

export const careersPageType = defineType({
  name: 'careersPage',
  title: 'Careers Page',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Page Identifier', type: 'string', initialValue: 'Careers Page', readOnly: true }),
    defineField({ name: 'bannerImage', title: 'Careers Header Banner', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'eyebrowEn', title: 'Eyebrow (English)', type: 'string' }),
    defineField({ name: 'eyebrowAr', title: 'Eyebrow (Arabic)', type: 'string' }),
    defineField({ name: 'pageTitleEn', title: 'Page Title (English)', type: 'string' }),
    defineField({ name: 'pageTitleAr', title: 'Page Title (Arabic)', type: 'string' }),
    defineField({ name: 'pageDescEn', title: 'Description (English)', type: 'text', rows: 3 }),
    defineField({ name: 'pageDescAr', title: 'Description (Arabic)', type: 'text', rows: 3 }),
    defineField({ name: 'heroButtonEn', title: 'Hero Button (English)', type: 'string' }),
    defineField({ name: 'heroButtonAr', title: 'Hero Button (Arabic)', type: 'string' }),
    defineField({ name: 'heroSideTextEn', title: 'Hero Side Message (English)', type: 'text', rows: 4 }),
    defineField({ name: 'heroSideTextAr', title: 'Hero Side Message (Arabic)', type: 'text', rows: 4 }),
    defineField({ name: 'vacanciesEyebrowEn', title: 'Vacancies Eyebrow (English)', type: 'string' }),
    defineField({ name: 'vacanciesEyebrowAr', title: 'Vacancies Eyebrow (Arabic)', type: 'string' }),
    defineField({ name: 'vacanciesTitleEn', title: 'Vacancies Heading (English)', type: 'string' }),
    defineField({ name: 'vacanciesTitleAr', title: 'Vacancies Heading (Arabic)', type: 'string' }),
    defineField({ name: 'vacanciesDescEn', title: 'Vacancies Description (English)', type: 'text', rows: 3 }),
    defineField({ name: 'vacanciesDescAr', title: 'Vacancies Description (Arabic)', type: 'text', rows: 3 }),
    defineField({ name: 'openLabelEn', title: 'Open Status Label (English)', type: 'string' }),
    defineField({ name: 'openLabelAr', title: 'Open Status Label (Arabic)', type: 'string' }),
    defineField({ name: 'closedLabelEn', title: 'Closed Status Label (English)', type: 'string' }),
    defineField({ name: 'closedLabelAr', title: 'Closed Status Label (Arabic)', type: 'string' }),
    defineField({ name: 'viewDetailsEn', title: 'View Details Label (English)', type: 'string' }),
    defineField({ name: 'viewDetailsAr', title: 'View Details Label (Arabic)', type: 'string' }),
    defineField({ name: 'postedLabelEn', title: 'Posted Date Label (English)', type: 'string' }),
    defineField({ name: 'postedLabelAr', title: 'Posted Date Label (Arabic)', type: 'string' }),
    defineField({ name: 'emptyMessageEn', title: 'No Vacancies Message (English)', type: 'string' }),
    defineField({ name: 'emptyMessageAr', title: 'No Vacancies Message (Arabic)', type: 'string' }),
    defineField({ name: 'cultureImage', title: 'Why Work With Us Image', type: 'image', options: { hotspot: true } }),
  ],
})
