import { defineField, defineType } from 'sanity'

export const jobType = defineType({
  name: 'job',
  title: 'Vacancy',
  type: 'document',
  fields: [
    defineField({ name: 'titleEn', title: 'Job Title (English)', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({ name: 'titleAr', title: 'Job Title (Arabic)', type: 'string' }),
    defineField({ name: 'slug', title: 'URL Slug', type: 'slug', options: { source: 'titleEn', maxLength: 96 }, validation: (Rule) => Rule.required() }),
    defineField({ name: 'departmentEn', title: 'Department (English)', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({ name: 'departmentAr', title: 'Department (Arabic)', type: 'string' }),
    defineField({ name: 'locationEn', title: 'Location (English)', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({ name: 'locationAr', title: 'Location (Arabic)', type: 'string' }),
    defineField({ name: 'employmentType', title: 'Employment Type', type: 'string', options: { list: ['Full-time', 'Part-time', 'Contract', 'Internship'], layout: 'radio' }, initialValue: 'Full-time' }),
    defineField({ name: 'employmentTypeAr', title: 'Employment Type (Arabic)', type: 'string' }),
    defineField({ name: 'descriptionEn', title: 'Detailed Description (English)', type: 'text', rows: 7 }),
    defineField({ name: 'descriptionAr', title: 'Detailed Description (Arabic)', type: 'text', rows: 7 }),
    defineField({ name: 'requirementsEn', title: 'Requirements (English)', type: 'text', rows: 7 }),
    defineField({ name: 'requirementsAr', title: 'Requirements (Arabic)', type: 'text', rows: 7 }),
    defineField({ name: 'companyEn', title: 'Company (English)', type: 'string', initialValue: 'ALMATAR Oil' }),
    defineField({ name: 'companyAr', title: 'Company (Arabic)', type: 'string' }),
    defineField({ name: 'reportsToEn', title: 'Reports To (English)', type: 'string' }),
    defineField({ name: 'reportsToAr', title: 'Reports To (Arabic)', type: 'string' }),
    defineField({ name: 'sectorEn', title: 'Sector (English)', type: 'string' }),
    defineField({ name: 'sectorAr', title: 'Sector (Arabic)', type: 'string' }),
    defineField({ name: 'experienceEn', title: 'Experience (English)', type: 'string' }),
    defineField({ name: 'experienceAr', title: 'Experience (Arabic)', type: 'string' }),
    defineField({ name: 'educationEn', title: 'Education (English)', type: 'string' }),
    defineField({ name: 'educationAr', title: 'Education (Arabic)', type: 'string' }),
    defineField({ name: 'languageEn', title: 'Language (English)', type: 'string' }),
    defineField({ name: 'languageAr', title: 'Language (Arabic)', type: 'string' }),
    defineField({ name: 'summaryEn', title: 'Job Summary (English)', type: 'text', rows: 6 }),
    defineField({ name: 'summaryAr', title: 'Job Summary (Arabic)', type: 'text', rows: 6 }),
    defineField({ name: 'responsibilitiesEn', title: 'Key Responsibilities (English)', type: 'text', rows: 8, description: 'Use one bullet per line.' }),
    defineField({ name: 'responsibilitiesAr', title: 'Key Responsibilities (Arabic)', type: 'text', rows: 8 }),
    defineField({ name: 'qualificationsEn', title: 'Education & Qualifications (English)', type: 'text', rows: 7 }),
    defineField({ name: 'qualificationsAr', title: 'Education & Qualifications (Arabic)', type: 'text', rows: 7 }),
    defineField({ name: 'experienceRequirementsEn', title: 'Experience Requirements (English)', type: 'text', rows: 7 }),
    defineField({ name: 'experienceRequirementsAr', title: 'Experience Requirements (Arabic)', type: 'text', rows: 7 }),
    defineField({ name: 'workEnvironmentEn', title: 'Work Environment (English)', type: 'text', rows: 7 }),
    defineField({ name: 'workEnvironmentAr', title: 'Work Environment (Arabic)', type: 'text', rows: 7 }),
    defineField({ name: 'heroImage', title: 'Vacancy Hero Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'applicationEmail', title: 'Application Email', type: 'string', initialValue: 'hr@almatar.com' }),
    defineField({ name: 'isOpen', title: 'Open for Applications', type: 'boolean', initialValue: true }),
    defineField({ name: 'order', title: 'Display Order', type: 'number', initialValue: 0 }),
  ],
  preview: {
    select: { title: 'titleEn', department: 'departmentEn', location: 'locationEn', isOpen: 'isOpen' },
    prepare({ title, department, location, isOpen }) {
      return { title: `${isOpen ? '🟢' : '⚪'} ${title || 'Untitled vacancy'}`, subtitle: `${department || 'Department'} · ${location || 'Location'}` }
    },
  },
})
