import { defineArrayMember, defineField, defineType } from 'sanity'

const textPair = (name: string, title: string, type: 'string' | 'text' = 'string') => [
  defineField({ name: `${name}En`, title: `${title} (English)`, type, ...(type === 'text' ? { rows: 3 } : {}) }),
  defineField({ name: `${name}Ar`, title: `${title} (Arabic)`, type, ...(type === 'text' ? { rows: 3 } : {}) }),
]

const bilingualObject = (title: string, fields: any[] = []) => defineArrayMember({
  type: 'object',
  title,
  fields: [...textPair('title', 'Title'), ...fields],
})

export const qhseSafetyProtocolType = defineType({
  name: 'qhseSafetyProtocol',
  title: 'Safety Protocol',
  type: 'object',
  fields: [
    ...textPair('title', 'Title'),
    defineField({ name: 'code', title: 'Reference Code', type: 'string' }),
    defineField({ name: 'image', title: 'Protocol Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'bulletsEn', title: 'Bullets (English)', type: 'array', of: [defineArrayMember({ type: 'string' })] }),
    defineField({ name: 'bulletsAr', title: 'Bullets (Arabic)', type: 'array', of: [defineArrayMember({ type: 'string' })] }),
  ],
})

export const qhsePageType = defineType({
  name: 'qhsePage',
  title: 'QHSE Page',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Page Identifier', type: 'string', initialValue: 'QHSE Page', readOnly: true }),
    defineField({ name: 'heroImage', title: 'Hero Image', type: 'image', options: { hotspot: true } }),
    ...textPair('heroEyebrow', 'Hero Eyebrow'),
    ...textPair('heroTitle', 'Hero Title'),
    ...textPair('heroDescription', 'Hero Description', 'text'),
    ...textPair('commitmentEyebrow', 'Commitment Eyebrow'),
    ...textPair('commitmentTitle', 'Commitment Title'),
    ...textPair('commitmentDescription', 'Commitment Description', 'text'),
    defineField({ name: 'commitmentImage', title: 'Commitment Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'commitmentCards', title: 'Commitment Cards', type: 'array', of: [bilingualObject('Commitment Card', [defineField({ name: 'icon', title: 'Icon Name', type: 'string', description: 'Examples: calendar, shield, globe, chart.' }), ...textPair('detail', 'Detail', 'text')])]}),
    ...textPair('policyEyebrow', 'Policy Eyebrow'),
    ...textPair('policyTitle', 'Policy Title'),
    defineField({ name: 'policyBullets', title: 'Policy Bullets', type: 'array', of: [bilingualObject('Policy Bullet', [defineField({ name: 'icon', title: 'Icon Name', type: 'string' })])] }),
    ...textPair('objectivesEyebrow', 'Objectives Eyebrow'),
    ...textPair('objectivesTitle', 'Objectives Title'),
    defineField({ name: 'objectives', title: 'QHSE Objectives Table', type: 'array', of: [defineArrayMember({ type: 'object', fields: [...textPair('objective', 'Objective'), ...textPair('kpi', 'KPI'), ...textPair('target', 'Target')] })] }),
    ...textPair('governanceEyebrow', 'Governance Eyebrow'),
    ...textPair('governanceTitle', 'Governance Title'),
    defineField({ name: 'governanceCards', title: 'Governance Cards', type: 'array', of: [bilingualObject('Governance Card', [defineField({ name: 'icon', title: 'Icon Name', type: 'string' }), ...textPair('detail', 'Detail', 'text')])] }),
    ...textPair('protocolsEyebrow', 'Protocols Eyebrow'),
    ...textPair('protocolsTitle', 'Protocols Title'),
    defineField({ name: 'protocols', title: 'Critical Safety Protocols', type: 'array', of: [defineArrayMember({ type: 'qhseSafetyProtocol' })] }),
    ...textPair('toleranceEyebrow', 'Zero-Tolerance Eyebrow'),
    ...textPair('toleranceTitle', 'Zero-Tolerance Title'),
    defineField({ name: 'tolerancePolicies', title: 'Zero-Tolerance Policies', type: 'array', of: [defineArrayMember({ type: 'object', fields: [...textPair('policy', 'Policy'), ...textPair('reference', 'Reference')] })] }),
    ...textPair('emergencyEyebrow', 'Emergency Eyebrow'),
    ...textPair('emergencyTitle', 'Emergency Title'),
    defineField({ name: 'emergencyRows', title: 'Emergency Response Table', type: 'array', of: [defineArrayMember({ type: 'object', fields: [...textPair('scenario', 'Scenario'), ...textPair('response', 'Response'), ...textPair('reference', 'Reference')] })] }),
    ...textPair('qmsEyebrow', 'QMS Eyebrow'),
    ...textPair('qmsTitle', 'QMS Title'),
    ...textPair('qmsDescription', 'QMS Description', 'text'),
    defineField({ name: 'qmsImage', title: 'QMS Image', type: 'image', options: { hotspot: true } }),
    ...textPair('qmsImageNote', 'QMS Image Note', 'text'),
    defineField({ name: 'certifications', title: 'Certifications', type: 'array', of: [bilingualObject('Certification', [defineField({ name: 'code', title: 'Standard / Code', type: 'string' }), ...textPair('detail', 'Detail')])] }),
    defineField({ name: 'qmsSteps', title: 'QMS Process Steps', type: 'array', of: [bilingualObject('QMS Step', [defineField({ name: 'icon', title: 'Icon Name', type: 'string' })])] }),
    ...textPair('auditEyebrow', 'Audit Eyebrow'),
    ...textPair('auditTitle', 'Audit Title'),
    defineField({ name: 'auditCards', title: 'Audit Cards', type: 'array', of: [bilingualObject('Audit Card', [defineField({ name: 'icon', title: 'Icon Name', type: 'string' }), ...textPair('detail', 'Detail', 'text')])] }),
    ...textPair('metricsEyebrow', 'Metrics Eyebrow'),
    ...textPair('metricsTitle', 'Metrics Title'),
    defineField({ name: 'metrics', title: 'HSE Metrics', type: 'array', of: [bilingualObject('Metric', [defineField({ name: 'value', title: 'Value', type: 'string' }), defineField({ name: 'icon', title: 'Icon Name', type: 'string' })])] }),
    ...textPair('documentsEyebrow', 'Documents Eyebrow'),
    ...textPair('documentsTitle', 'Documents Title'),
    defineField({ name: 'documents', title: 'QHSE Policy Documents', type: 'array', of: [defineArrayMember({ type: 'object', fields: [...textPair('policy', 'Policy'), ...textPair('reference', 'Reference'), defineField({ name: 'file', title: 'PDF Document', type: 'file', options: { accept: '.pdf' } }), defineField({ name: 'url', title: 'Fallback PDF URL', type: 'url' })] })] }),
    ...textPair('ctaTitle', 'CTA Title'),
    ...textPair('ctaDescription', 'CTA Description', 'text'),
    defineField({ name: 'ctaEmail', title: 'QHSE Email', type: 'string' }),
    defineField({ name: 'ctaImage', title: 'CTA Background Image', type: 'image', options: { hotspot: true } }),
  ],
  preview: { select: { title: 'title', media: 'heroImage' } },
})
