'use client';
import NextPageBanner from '@/components/NextPageBanner';
import ServiceIntroCard from '@/components/ServiceIntroCard';

const base='/images/policies-photo/services/almatar_total_field_all_photos/';
const services=[['02_heavy_haulage_transport-hd.webp','HEAVY HAULAGE & SPECIALIZED TRANSPORT'],['03_rig_and_site_mobilization-hd.webp','RIG & SITE MOBILIZATION'],['04_lifting_and_cranes-hd.webp','LIFTING AND CRANES'],['05_temporary_roads_site_preparation-hd.webp','TEMPORARY ROADS & SITE PREPARATION'],['06_modular_camps_facilities.webp','MODULAR CAMPS & FACILITIES'],['07_certified_engineers_operators.webp','CERTIFIED ENGINEERS & OPERATORS'],['08_catering_support.webp','CATERING SUPPORT'],['09_500_bbl_frac_tank_rental.webp','500 BBL FRAC TANK RENTAL'],['10_acid_storage_containment.webp','ACID STORAGE & CONTAINMENT']];
const rail=['WELL INTERVENTION SERVICES','COILED TUBING & NITROGEN PUMPING','STIMULATION & FRACTURING','ZONAL ISOLATION & CEMENTING','WELLHEAD & XMAS TREE SERVICES','SLICKLINE SERVICES','WELL TESTING & FLARING','DRILLING AND WORKOVER SERVICES','TOTAL FIELD CONSTRUCTION & MANPOWER LOGISTICS'];
const process=['PLANNING & ROUTE SURVEY','EQUIPMENT PREPARATION & MOBILIZATION','SITE SETUP & CONSTRUCTION','OPERATIONS SUPPORT','DEMOBILIZATION & SITE RESTORATION'];

export default function ConstructionPage(){
  return <div className="total-field-page tf-construction">
  <section className="tf-hero"><img src={`${base}01_hero_total_field_construction.webp`} alt="Total field construction and manpower logistics"/><div className="tf-hero-copy"><span>BUILDING SOLUTIONS ON THE GROUND</span><h1>TOTAL FIELD<br/>CONSTRUCTION &amp;<br/>MANPOWER LOGISTICS</h1><p>End-to-end field construction, heavy equipment transportation, site mobilization, certified technical manpower, camp management, catering services, 500 BBL frac tanks and containment solutions for onshore operations.</p><a href="#capabilities">REQUEST TECHNICAL SUPPORT&nbsp; →</a><a className="tf-outline-button" href="#capabilities">OUR CAPABILITIES</a></div><span className="tf-hero-side">PEOPLE<br/>EQUIPMENT<br/>INFRASTRUCTURE<br/>RESULTS</span></section>
  <ServiceIntroCard eyebrow="FIELD DELIVERY &amp; SUPPORT" title="Integrated Field Construction Solutions" description="ALMATAR provides complete construction, logistics, manpower and site-support services for safe, efficient and reliable onshore field delivery." image={`${base}02_heavy_haulage_transport-hd.webp`} imageAlt="Heavy field logistics equipment" />
  <section className="tf-strip">{rail.map((item,i)=><span className={i===8?'active':''} key={item}>♧<b>{item}</b></span>)}</section>
  <section className="tf-section tf-intro"><div><small>FROM BASE TO FIELD</small><h2>INTEGRATED FIELD DELIVERY</h2><p>We provide complete field construction and manpower logistics solutions to support your operations in the most challenging environments. From heavy transport to camp management, our integrated approach ensures safe, efficient and reliable project delivery.</p></div><div className="tf-intro-cards"><article><b>▣</b><h3>HEAVY LOGISTICS &amp;<br/>FLEET TRANSPORT</h3><p>Safe and reliable transportation of equipment and materials to remote locations.</p></article><article><b>♧</b><h3>TECHNICAL MANPOWER<br/>&amp; SITE CATERING</h3><p>Certified personnel, camp management and catering services.</p></article><article><b>△</b><h3>500 BBL FRAC TANKS<br/>&amp; CONTAINMENT</h3><p>Rental and installation of tanks with complete containment solutions.</p></article></div></section>
  <section className="tf-section tf-process"><small>LOGISTICS FROM START TO SITE</small><h2>OUR MOBILIZATION PROCESS</h2><p>A streamlined logistics chain from our base to your remote field location.</p><div className="tf-route">{[['06_modular_camps_facilities.webp','ALMATAR WAREHOUSE / BASE'],['02_heavy_haulage_transport-hd.webp','EQUIPMENT PREPARATION & LOADING'],['03_rig_and_site_mobilization-hd.webp','TRANSPORTATION & ROUTE MANAGEMENT'],['04_lifting_and_cranes-hd.webp','SITE MOBILIZATION & OFFLOADING'],['01_hero_total_field_construction.webp','REMOTE OILFIELD SITE']].map(([img,title])=><article key={title}><img src={`${base}${img}`} alt={title}/><strong>{title}</strong></article>)}</div></section>
  <section id="capabilities" className="tf-section"><small>OUR CAPABILITIES</small><h2>COMPLETE SOLUTIONS FOR FIELD OPERATIONS</h2><div className="tf-capabilities">{services.map(([image,title])=><article key={title}><img src={`${base}${image}`} alt={title}/><h3>{title}</h3><p>Complete field support with safe, reliable and certified solutions for demanding operations.</p></article>)}<article className="tf-cta"><h3>TAILORED SOLUTIONS<br/>FOR YOUR PROJECT</h3><a href="/contact">DISCUSS YOUR REQUIREMENTS →</a></article></div></section>
  <section className="tf-process tf-process-steps tf-section"><small>PROJECT LIFECYCLE</small><h2>FROM PLANNING TO DEMOBILIZATION</h2><div>{process.map((x,i)=><article key={x}><b>{String(i+1).padStart(2,'0')}</b><strong>{x}</strong><p>Detailed planning, execution and support for safe project delivery.</p></article>)}</div></section>
  <section className="tf-feature-grid"><article><img src={`${base}11_heavy_equipment_clean.webp`} alt="Heavy equipment real capabilities"/><h2>HEAVY EQUIPMENT.<br/>REAL CAPABILITIES.</h2></article><article><img src={`${base}12_modular_camps_clean.webp`} alt="Modular camps in the field"/><h2>MODULAR CAMPS.<br/>A HOME IN THE FIELD.</h2></article></section>
  <section className="tf-feature-grid tf-people"><article><img src={`${base}13_disciplined_crews_clean.webp`} alt="Disciplined crews"/><div><small>OUR PEOPLE</small><h2>DISCIPLINED CREWS.<br/>PROVEN PERFORMANCE.</h2><p>Our success is built on our people. We provide certified engineers, operators and field personnel with the right skills, experience and mindset to deliver in demanding environments.</p></div></article><article><img src={`${base}14_safety_people_environment_clean.webp`} alt="Safety, people and environment"/><div><small>HSE &amp; ENVIRONMENT</small><h2>SAFETY. PEOPLE. ENVIRONMENT.<br/>ALWAYS FIRST.</h2><p>We maintain the highest standards of HSE in all our construction and logistics operations, ensuring safe lifting, camp operations and environmental containment.</p></div></article></section>
  <section className="tf-stats"><b>50+<small>FLEET UNITS<br/>Available for deployment</small></b><b>200+<small>TECHNICAL PERSONNEL<br/>Engineers, operators &amp; support staff</small></b><b>NATIONWIDE<small>RESPONSE COVERAGE<br/>Rapid mobilization to any field location</small></b><b>500 BBL<small>TANK CAPACITY<br/>Frac tanks with full containment</small></b></section>
  <NextPageBanner title="LET’S MOBILIZE YOUR NEXT FIELD PROJECT" subtitle="Reliable logistics. Skilled people. Complete field support. Wherever you operate." link="/contact" bgImage={`${base}01_hero_total_field_construction.webp`}/>
</div>}
