'use client';

import NextPageBanner from './NextPageBanner';
import ServiceIntroCard from './ServiceIntroCard';
import { useLanguage } from '@/context/LanguageContext';
import { useSanityContent } from '@/sanity/lib/fetchData';
import { WEBSITE_PAGE_QUERY } from '@/sanity/lib/queries';
import { getImageUrl } from '@/sanity/lib/image';

const base = '/images/policies-photo/services/almatar_total_field_all_photos/';

const content = {
  en: {
    heroEyebrow: 'BUILDING SOLUTIONS ON THE GROUND', heroTitle: <>TOTAL FIELD<br />CONSTRUCTION &<br />MANPOWER LOGISTICS</>, heroDescription: 'End-to-end field construction, heavy equipment transportation, site mobilization, certified technical manpower, camp management, catering services, 500 BBL frac tanks and containment solutions for onshore operations.', heroSupport: 'REQUEST TECHNICAL SUPPORT', heroCapabilities: 'OUR CAPABILITIES', heroSide: <>PEOPLE<br />EQUIPMENT<br />INFRASTRUCTURE<br />RESULTS</>,
    introEyebrow: 'FIELD DELIVERY & SUPPORT', introTitle: 'Integrated Field Construction Solutions', introDescription: 'ALMATAR provides complete construction, logistics, manpower and site-support services for safe, efficient and reliable onshore field delivery.', fromBase: 'FROM BASE TO FIELD', deliveryTitle: 'INTEGRATED FIELD DELIVERY', deliveryDescription: 'We provide complete field construction and manpower logistics solutions to support your operations in the most challenging environments. From heavy transport to camp management, our integrated approach ensures safe, efficient and reliable project delivery.',
    introCards: [['HEAVY LOGISTICS &\nFLEET TRANSPORT', 'Safe and reliable transportation of equipment and materials to remote locations.'], ['TECHNICAL MANPOWER\n& SITE CATERING', 'Certified personnel, camp management and catering services.'], ['500 BBL FRAC TANKS\n& CONTAINMENT', 'Rental and installation of tanks with complete containment solutions.']],
    logisticsEyebrow: 'LOGISTICS FROM START TO SITE', logisticsTitle: 'OUR MOBILIZATION PROCESS', logisticsDescription: 'A streamlined logistics chain from our base to your remote field location.', route: ['ALMATAR WAREHOUSE / BASE', 'EQUIPMENT PREPARATION & LOADING', 'TRANSPORTATION & ROUTE MANAGEMENT', 'SITE MOBILIZATION & OFFLOADING', 'REMOTE OILFIELD SITE'], capabilitiesEyebrow: 'OUR CAPABILITIES', capabilitiesTitle: 'COMPLETE SOLUTIONS FOR FIELD OPERATIONS', capabilityDescription: 'Complete field support with safe, reliable and certified solutions for demanding operations.', tailored: <>TAILORED SOLUTIONS<br />FOR YOUR PROJECT</>, discuss: 'DISCUSS YOUR REQUIREMENTS', lifecycleEyebrow: 'PROJECT LIFECYCLE', lifecycleTitle: 'FROM PLANNING TO DEMOBILIZATION', process: ['PLANNING & ROUTE SURVEY', 'EQUIPMENT PREPARATION & MOBILIZATION', 'SITE SETUP & CONSTRUCTION', 'OPERATIONS SUPPORT', 'DEMOBILIZATION & SITE RESTORATION'], processDescription: 'Detailed planning, execution and support for safe project delivery.', features: [<>HEAVY EQUIPMENT.<br />REAL CAPABILITIES.</>, <>MODULAR CAMPS.<br />A HOME IN THE FIELD.</>], people: [['OUR PEOPLE', <>DISCIPLINED CREWS.<br />PROVEN PERFORMANCE.</>, 'Our success is built on our people. We provide certified engineers, operators and field personnel with the right skills, experience and mindset to deliver in demanding environments.'], ['HSE & ENVIRONMENT', <>SAFETY. PEOPLE. ENVIRONMENT.<br />ALWAYS FIRST.</>, 'We maintain the highest standards of HSE in all our construction and logistics operations, ensuring safe lifting, camp operations and environmental containment.']], stats: [['50+', 'FLEET UNITS\nAvailable for deployment'], ['200+', 'TECHNICAL PERSONNEL\nEngineers, operators & support staff'], ['NATIONWIDE', 'RESPONSE COVERAGE\nRapid mobilization to any field location'], ['500 BBL', 'TANK CAPACITY\nFrac tanks with full containment']], ctaTitle: 'LET’S MOBILIZE YOUR NEXT FIELD PROJECT', ctaDescription: 'Reliable logistics. Skilled people. Complete field support. Wherever you operate.',
  },
  ar: {
    heroEyebrow: 'نبني الحلول على أرض الواقع', heroTitle: <>الإنشاءات الحقلية<br />المتكاملة واللوجستيات<br />والكوادر</>, heroDescription: 'إنشاءات حقلية متكاملة، نقل المعدات الثقيلة، تجهيز المواقع، كوادر فنية معتمدة، إدارة المخيمات، خدمات الإعاشة، خزانات فراك بسعة 500 برميل وحلول احتواء للعمليات البرية.', heroSupport: 'اطلب الدعم الفني', heroCapabilities: 'قدراتنا', heroSide: <>الكوادر<br />المعدات<br />البنية التحتية<br />النتائج</>,
    introEyebrow: 'التنفيذ والدعم الميداني', introTitle: 'حلول متكاملة للإنشاءات الحقلية', introDescription: 'تقدم المطر خدمات الإنشاءات واللوجستيات والكوادر ودعم المواقع بشكل متكامل لتسليم عمليات برية آمنة وفعالة وموثوقة.', fromBase: 'من القاعدة إلى الحقل', deliveryTitle: 'تنفيذ ميداني متكامل', deliveryDescription: 'نوفر حلولاً متكاملة للإنشاءات الحقلية ولوجستيات الكوادر لدعم عملياتكم في أكثر البيئات تحدياً. ومن النقل الثقيل إلى إدارة المخيمات، يضمن نهجنا المتكامل تسليم المشاريع بأمان وكفاءة وموثوقية.',
    introCards: [['اللوجستيات الثقيلة\nوأسطول النقل', 'نقل آمن وموثوق للمعدات والمواد إلى المواقع النائية.'], ['الكوادر الفنية\nوإعاشة المواقع', 'كوادر معتمدة وإدارة مخيمات وخدمات إعاشة.'], ['خزانات فراك 500 برميل\nوالاحتواء', 'تأجير وتركيب الخزانات مع حلول احتواء متكاملة.']],
    logisticsEyebrow: 'لوجستيات من البداية إلى الموقع', logisticsTitle: 'عملية التجهيز والنقل لدينا', logisticsDescription: 'سلسلة لوجستية مبسطة من قاعدتنا إلى موقعكم الحقلي النائي.', route: ['مستودع / قاعدة المطر', 'تجهيز المعدات وتحميلها', 'النقل وإدارة المسار', 'تجهيز الموقع والتفريغ', 'موقع حقل نفطي ناءٍ'], capabilitiesEyebrow: 'قدراتنا', capabilitiesTitle: 'حلول متكاملة للعمليات الحقلية', capabilityDescription: 'دعم ميداني متكامل بحلول آمنة وموثوقة ومعتمدة للعمليات المتطلبة.', tailored: <>حلول مخصصة<br />لمشروعكم</>, discuss: 'ناقشوا متطلباتكم', lifecycleEyebrow: 'دورة حياة المشروع', lifecycleTitle: 'من التخطيط إلى إنهاء التجهيزات', process: ['التخطيط ومسح المسار', 'تجهيز المعدات والنقل', 'تجهيز الموقع والإنشاء', 'دعم العمليات', 'إنهاء التجهيزات واستعادة الموقع'], processDescription: 'تخطيط وتنفيذ ودعم تفصيليان لتسليم المشاريع بأمان.', features: [<>معدات ثقيلة.<br />قدرات حقيقية.</>, <>مخيمات متنقلة.<br />منزل في الحقل.</>], people: [['كوادرنا', <>فرق منضبطة.<br />أداء مثبت.</>, 'يرتكز نجاحنا على كوادرنا. نوفر مهندسين ومشغلين وموظفي حقول معتمدين يمتلكون المهارات والخبرة والعقلية المناسبة للنجاح في البيئات المتطلبة.'], ['الصحة والسلامة والبيئة', <>السلامة والكوادر والبيئة.<br />دائماً أولاً.</>, 'نحافظ على أعلى معايير الصحة والسلامة والبيئة في جميع عمليات الإنشاءات واللوجستيات، بما في ذلك الرفع الآمن وعمليات المخيمات والاحتواء البيئي.']], stats: [['50+', 'وحدة أسطول\nمتاحة للتجهيز'], ['200+', 'كادر فني\nمهندسون ومشغّلون وموظفو دعم'], ['تغطية شاملة', 'استجابة ميدانية\nتجهيز سريع لأي موقع حقلي'], ['500 برميل', 'سعة الخزانات\nخزانات فراك باحتواء كامل']], ctaTitle: 'لنجهّز مشروعكم الحقلي القادم', ctaDescription: 'لوجستيات موثوقة. كوادر ماهرة. دعم ميداني متكامل، أينما تعملون.',
  },
};

const capabilities = [['02_heavy_haulage_transport-hd.webp', ['HEAVY HAULAGE & SPECIALIZED TRANSPORT', 'النقل الثقيل والنقل المتخصص']], ['03_rig_and_site_mobilization-hd.webp', ['RIG & SITE MOBILIZATION', 'تجهيز الحفارات والمواقع']], ['04_lifting_and_cranes-hd.webp', ['LIFTING AND CRANES', 'الرفع والرافعات']], ['05_temporary_roads_site_preparation-hd.webp', ['TEMPORARY ROADS & SITE PREPARATION', 'الطرق المؤقتة وتجهيز المواقع']], ['06_modular_camps_facilities.webp', ['MODULAR CAMPS & FACILITIES', 'المخيمات والمرافق المتنقلة']], ['07_certified_engineers_operators.webp', ['CERTIFIED ENGINEERS & OPERATORS', 'مهندسون ومشغّلون معتمدون']], ['08_catering_support.webp', ['CATERING SUPPORT', 'دعم الإعاشة']], ['09_500_bbl_frac_tank_rental.webp', ['500 BBL FRAC TANK RENTAL', 'تأجير خزانات فراك 500 برميل']], ['10_acid_storage_containment.webp', ['ACID STORAGE & CONTAINMENT', 'تخزين الأحماض واحتواؤها']]];
const routeImages = ['06_modular_camps_facilities.webp', '02_heavy_haulage_transport-hd.webp', '03_rig_and_site_mobilization-hd.webp', '04_lifting_and_cranes-hd.webp', '01_hero_total_field_construction.webp'];

export default function LocalizedConstructionPage({ cmsData }) {
  const { lang } = useLanguage();
  const fetchedData = useSanityContent('websitePage', WEBSITE_PAGE_QUERY, { pageKey: 'construction' });
  const data = cmsData || fetchedData;
  const text = content[lang] || content.en;
  const index = lang === 'ar' ? 1 : 0;
  const isArabic = lang === 'ar';

  const heroImg = getImageUrl(data?.heroImage || data?.image || data?.pageContent?.heroImage, `${base}01_hero_total_field_construction.webp`);
  const heroEyebrow = (isArabic ? (data?.heroEyebrowAr || data?.pageContent?.heroEyebrowAr) : (data?.heroEyebrowEn || data?.pageContent?.heroEyebrowEn)) || text.heroEyebrow;
  const heroTitle = (isArabic ? (data?.heroTitleAr || data?.pageContent?.heroTitleAr) : (data?.heroTitleEn || data?.pageContent?.heroTitleEn)) || text.heroTitle;
  const heroDescription = (isArabic ? (data?.heroDescriptionAr || data?.pageContent?.heroDescriptionAr) : (data?.heroDescriptionEn || data?.pageContent?.heroDescriptionEn)) || text.heroDescription;

  const firstSection = data?.sections?.[0] || data?.pageContent?.sections?.[0];
  const introImg = getImageUrl(firstSection?.image || data?.introImage || data?.pageContent?.introImage, `${base}02_heavy_haulage_transport-hd.webp`);
  const introEyebrow = (isArabic ? (firstSection?.eyebrowAr || data?.introEyebrowAr) : (firstSection?.eyebrowEn || data?.introEyebrowEn)) || text.introEyebrow;
  const introTitle = (isArabic ? (firstSection?.titleAr || data?.introTitleAr) : (firstSection?.titleEn || data?.introTitleEn)) || text.introTitle;
  const introDescription = (isArabic ? (firstSection?.descriptionAr || data?.introDescriptionAr) : (firstSection?.descriptionEn || data?.introDescriptionEn)) || text.introDescription;

  const ctaImg = getImageUrl(data?.cta?.image || data?.ctaImage || data?.pageContent?.ctaImage, `${base}01_hero_total_field_construction.webp`);
  const ctaTitle = (isArabic ? (data?.cta?.titleAr || data?.ctaTitleAr || data?.pageContent?.ctaTitleAr) : (data?.cta?.titleEn || data?.ctaTitleEn || data?.pageContent?.ctaTitleEn)) || text.ctaTitle;
  const ctaDescription = (isArabic ? (data?.cta?.descriptionAr || data?.ctaDescriptionAr || data?.pageContent?.ctaDescriptionAr) : (data?.cta?.descriptionEn || data?.ctaDescriptionEn || data?.pageContent?.ctaDescriptionEn)) || text.ctaDescription;

  return <div className="total-field-page tf-construction" dir={isArabic ? 'rtl' : 'ltr'}>
    <section className="tf-hero"><img src={heroImg} alt={typeof heroTitle === 'string' ? heroTitle : text.introTitle} /><div className="tf-hero-copy"><span>{heroEyebrow}</span><h1>{heroTitle}</h1><p>{heroDescription}</p><a href="#capabilities">{text.heroSupport} →</a><a className="tf-outline-button" href="#capabilities">{text.heroCapabilities}</a></div><span className="tf-hero-side">{text.heroSide}</span></section>
    <ServiceIntroCard eyebrow={introEyebrow} title={introTitle} description={introDescription} image={introImg} imageAlt={typeof introTitle === 'string' ? introTitle : text.introTitle} />
    <section className="tf-section tf-intro"><div><small>{text.fromBase}</small><h2>{text.deliveryTitle}</h2><p>{text.deliveryDescription}</p></div><div className="tf-intro-cards">{text.introCards.map(([title, description], itemIndex) => <article key={title}><b>{['▣', '♧', '△'][itemIndex]}</b><h3>{title.split('\n').map((line) => <span key={line}>{line}<br /></span>)}</h3><p>{description}</p></article>)}</div></section>
    <section className="tf-section tf-process"><small>{text.logisticsEyebrow}</small><h2>{text.logisticsTitle}</h2><p>{text.logisticsDescription}</p><div className="tf-route">{text.route.map((title, itemIndex) => <article key={title}><img src={`${base}${routeImages[itemIndex]}`} alt={title} /><strong>{title}</strong></article>)}</div></section>
    <section id="capabilities" className="tf-section"><small>{text.capabilitiesEyebrow}</small><h2>{text.capabilitiesTitle}</h2><div className="tf-capabilities">{capabilities.map(([image, title]) => <article key={image}><img src={`${base}${image}`} alt={title[index]} /><h3>{title[index]}</h3><p>{text.capabilityDescription}</p></article>)}<article className="tf-cta"><h3>{text.tailored}</h3><a href="/contact">{text.discuss} →</a></article></div></section>
    <section className="tf-process tf-process-steps tf-section"><small>{text.lifecycleEyebrow}</small><h2>{text.lifecycleTitle}</h2><div>{text.process.map((item, itemIndex) => <article key={item}><b>{String(itemIndex + 1).padStart(2, '0')}</b><strong>{item}</strong><p>{text.processDescription}</p></article>)}</div></section>
    <section className="tf-feature-grid"><article><img src={`${base}11_heavy_equipment_clean.webp`} alt={text.features[0]} /><h2>{text.features[0]}</h2></article><article><img src={`${base}12_modular_camps_clean.webp`} alt={text.features[1]} /><h2>{text.features[1]}</h2></article></section>
    <section className="tf-feature-grid tf-people">{text.people.map(([eyebrow, title, description], itemIndex) => <article key={eyebrow}><img src={`${base}${itemIndex === 0 ? '13_disciplined_crews_clean.webp' : '14_safety_people_environment_clean.webp'}`} alt={eyebrow} /><div><small>{eyebrow}</small><h2>{title}</h2><p>{description}</p></div></article>)}</section>
    <section className="tf-stats">{text.stats.map(([value, label]) => <b key={value}>{value}<small>{label}</small></b>)}</section>
    <NextPageBanner title={ctaTitle} subtitle={ctaDescription} link="/contact" bgImage={ctaImg} />
  </div>;
}
